/*
============================================================
 Example queries for the Energy Operations Platform
============================================================

These queries demonstrate basic selection, filtering, joins,
aggregations and lookups across the current database schema.

============================================================
*/

-- ============================================================
-- 1. Asset overview
-- Lists all configured assets.
-- ============================================================
SELECT *
FROM assets
ORDER BY asset_id;


-- ============================================================
-- 2. Measurement overview
-- Lists all measurements in chronological order.
-- ============================================================
SELECT *
FROM measurements
ORDER BY measurement_time, asset_id;


-- ============================================================
-- 3. Measurements for one asset
-- Lists all measurements belonging to asset 1.
-- ============================================================
SELECT *
FROM measurements
WHERE asset_id = 1
ORDER BY measurement_time;


-- ============================================================
-- 4. Measurements above a power threshold
-- Lists measurements with active power above 100 MW.
-- ============================================================
SELECT *
FROM measurements
WHERE active_power_kw > 100000
ORDER BY active_power_kw DESC;


-- ============================================================
-- 5. Measurements by source
-- Lists all measurements generated by the simulation.
-- ============================================================
SELECT *
FROM measurements
WHERE source = 'simulation'
ORDER BY measurement_time, asset_id;


-- ============================================================
-- 6. Valid simulated measurements above a power threshold
-- Combines source, quality and power filters.
-- ============================================================
SELECT *
FROM measurements
WHERE source = 'simulation'
  AND quality_status = 'valid'
  AND active_power_kw > 100000
ORDER BY active_power_kw DESC;


-- ============================================================
-- 7. Measurements for one asset type
-- Lists measurements for all wind parks.
-- ============================================================
SELECT
    a.asset_name,
    at.asset_type_name,
    m.measurement_time,
    m.active_power_kw,
    m.quality_status
FROM measurements AS m
JOIN assets AS a
    ON a.asset_id = m.asset_id
JOIN asset_types AS at
    ON at.asset_type_id = a.asset_type_id
WHERE at.asset_type_name = 'wind_park'
ORDER BY a.asset_name, m.measurement_time;


-- ============================================================
-- 8. Joined asset and measurement data
-- Lists measurements together with asset and region data.
-- ============================================================
SELECT
    a.asset_code,
    a.asset_name,
    at.asset_type_name,
    at.asset_role,
    r.region_code,
    m.measurement_time,
    m.active_power_kw,
    m.quality_status
FROM measurements AS m
JOIN assets AS a
    ON a.asset_id = m.asset_id
JOIN asset_types AS at
    ON at.asset_type_id = a.asset_type_id
JOIN regions AS r
    ON r.region_id = a.region_id
ORDER BY a.asset_name, m.measurement_time;


-- ============================================================
-- 9. High-power measurements with asset context
-- Lists measurements above 100 MW together with asset details.
-- ============================================================
SELECT
    a.asset_name,
    at.asset_type_name,
    r.region_code,
    m.measurement_time,
    m.active_power_kw
FROM measurements AS m
JOIN assets AS a
    ON a.asset_id = m.asset_id
JOIN asset_types AS at
    ON at.asset_type_id = a.asset_type_id
JOIN regions AS r
    ON r.region_id = a.region_id
WHERE m.active_power_kw > 100000
ORDER BY m.active_power_kw DESC;


-- ============================================================
-- 10. Assets with high average active power
-- Shows only assets whose valid measurements average above 100 MW.
-- ============================================================
SELECT
    a.asset_id,
    a.asset_name,
    COUNT(m.measurement_id) AS number_of_measurements,
    ROUND(AVG(m.active_power_kw),2) AS average_active_power_kw,
    MIN(m.active_power_kw) AS minimum_active_power_kw,
    MAX(m.active_power_kw) AS maximum_active_power_kw
FROM assets AS a
JOIN measurements AS m
    ON m.asset_id = a.asset_id
WHERE m.quality_status = 'valid'
GROUP BY a.asset_id, a.asset_name
HAVING AVG(m.active_power_kw) > 100000
ORDER BY average_active_power_kw DESC;


-- ============================================================
-- 11. Measurement summary per asset
-- Shows count, average, minimum and maximum active power.
-- ============================================================
SELECT
    a.asset_id,
    a.asset_name,
    COUNT(m.measurement_id) AS number_of_measurements,
    ROUND(AVG(m.active_power_kw),2) AS average_active_power_kw,
    MIN(m.active_power_kw) AS minimum_active_power_kw,
    MAX(m.active_power_kw) AS maximum_active_power_kw
FROM assets AS a
LEFT JOIN measurements AS m
    ON m.asset_id = a.asset_id
GROUP BY a.asset_id, a.asset_name
ORDER BY average_active_power_kw ASC NULLS LAST;


-- ============================================================
-- 12. Regional master data
-- Lists all configured operational regions.
-- ============================================================
SELECT
    region_id,
    region_code,
    region_prefix,
    region_name,
    region_description
FROM regions
ORDER BY region_id;


-- ============================================================
-- 13. Asset type distribution by role
-- Counts configured asset types for each asset role.
-- ============================================================
SELECT
    asset_role,
    COUNT(*) AS number_of_asset_types
FROM asset_types
GROUP BY asset_role
ORDER BY asset_role;


-- ============================================================
-- 14. Asset overview with type and region
-- Lists assets with classification, location and rated power.
-- ============================================================
SELECT
    a.asset_code,
    a.asset_name,
    a.asset_location,
    at.asset_type_name,
    at.asset_role,
    r.region_code,
    a.rated_power_kw,
    a.operating_status
FROM assets AS a
JOIN asset_types AS at
    ON at.asset_type_id = a.asset_type_id
JOIN regions AS r
    ON r.region_id = a.region_id
ORDER BY a.asset_id;


-- ============================================================
-- 15. Asset distribution by region and role
-- Counts assets grouped by operational region and asset role.
-- ============================================================
SELECT
    r.region_code,
    at.asset_role,
    COUNT(*) AS number_of_assets
FROM assets AS a
JOIN regions AS r
    ON r.region_id = a.region_id
JOIN asset_types AS at
    ON at.asset_type_id = a.asset_type_id
GROUP BY r.region_code, at.asset_role
ORDER BY r.region_code, at.asset_role;


-- ============================================================
-- 16. Storage asset specifications
-- Lists technical specifications for all storage assets.
-- ============================================================
SELECT
    a.asset_code,
    a.asset_name,
    s.energy_capacity_kwh,
    s.max_charge_power_kw,
    s.max_discharge_power_kw,
    s.charge_efficiency_percent,
    s.discharge_efficiency_percent,
    s.min_state_of_charge_percent,
    s.max_state_of_charge_percent
FROM storage_specs AS s
JOIN assets AS a
    ON a.asset_id = s.asset_id
ORDER BY a.asset_id;
